name: weather_app
description: "A weather app that provides current weather information and forecasts."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"  # Path to your icon file
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"  # Optional for Android adaptive icon
  adaptive_icon_background: "#FF5700"